# Gmail Attachment Downloader Configuration
# This file controls how the application behaves

# Gmail API settings
gmail:
  # Path to OAuth2 credentials from Google Cloud Console
  credentials_file: "config/credentials.json"
  
  # Where to store authentication tokens
  token_file: "config/token.json"
  
  # API rate limiting (respect Gmail quotas)
  requests_per_minute: 250
  max_retries: 3

# Email filtering options
filters:
  # Specific senders to monitor (empty = all senders)
  senders: []
    # - "important@company.com"
    # - "reports@system.com"
  
  # File types to download
  extensions:
    - ".pdf"
    - ".docx"
    - ".xlsx"
    - ".csv"
    - ".txt"
  
  # Date filtering (YYYY-MM-DD format)
  after_date: null   # Download emails after this date
  before_date: null  # Download emails before this date
  
  # File size limits
  min_size: 1024          # 1 KB minimum
  max_size: 52428800      # 50 MB maximum
  
  # Subject filtering
  subject_keywords: []           # Include emails with these words
  subject_exclude_keywords:      # Exclude emails with these words
    - "spam"
    - "promotional"

# Download and organization settings
download:
  # Where to save attachments
  base_dir: "./downloads"
  
  # How to organize files: sender, date, sender_date, flat
  organize_by: "sender"
  
  # File naming: original, timestamp, uuid
  naming_strategy: "original"
  
  # Whether to overwrite existing files
  overwrite_existing: false
  
  # Parallel downloads (be reasonable)
  max_concurrent_downloads: 3

# Real-time monitoring settings (for watch mode)
watch:
  # How often to check for new emails (seconds)
  check_interval: 30
  
  # Show desktop notifications
  show_notifications: true
  
  # Maximum watch time (minutes, 0 = infinite)
  max_runtime_minutes: 0

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  
  # Log file location (null = console only)
  file_path: "logs/gmail_downloader.log"
  
  # Keep this many old log files
  backup_count: 5
